server:
  port: 8080
  servlet:
    context-path: /



spring:

  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000

  mail:
    host: smtp.sina.com # 使用新浪的smtp服务
    port: 465
    username: xingchen066@sina.com
    password: af5f4cb51a7e6e83
    protocol: smtps # 使用加密协议
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true  # 发送邮件时使用ssl安全连接

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3000
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      # 配置kafka的组id，可以在kafka的配置文件consumer.properties中找到
      group-id: test-consumer-group
      # 设置是否自动提交
      enable-auto-commit: true
      # 设置自动提交频率
      auto-commit-interval: 3000



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cgc.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true



# 配置日志级别
logging:
  file: E:/IDEAWorkPlace/Log/community.log
  level:
    com.cgc.mapper:
      debug

community:
  path:
    upload: E:\IDEAWorkPlace\repository
    domain: http://localhost:8080
