server:
  port: 8080
  servlet:
    context-path: /

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  mail:
    host: smtp.sina.com # 使用新浪的smtp服务
    port: 465
    username: xingchen066@sina.com
    password: af5f4cb51a7e6e83
    protocol: smtps # 使用加密协议
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true  # 发送邮件时使用ssl安全连接

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cgc.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true


#  # redis
#  redis:
#    database: 11
#    host: localhost
#    port: 6379
#  # kafka
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: test-consumer-group
#      enable-auto-commit: true
#      auto-commit-interval: 3000 #ms
#  # elasticsearch
#  data:
#    elasticsearch:
#      cluster-name: nowcoder
#      cluster-nodes: 127.0.0.1:9300
#
#
## 加密参数
#jasypt:
#  encryptor:
#    password: test

# 配置日志级别
logging:
  file: E:/IDEAWorkPlace/Log/community.log
  level:
    com.cgc.mapper:
      debug

community:
  path:
    domain: http://localhost:8080
